using _1.DataAccessLayer.Company;
using _1.DataAccessLayer.Member;
using _1.DataAccessLayer.Sale_Orders;
using _2.DataTransferObject;
using _4.Utils;
using ApiTng.apiconnect;
using ApiTng.ApiExpress;
using ApiTng.Models;
using Newtonsoft.Json;
using NLog;
using Nuclex.Cloning;
using System;
using System.Collections.Generic;
using System.Data;
using System.IO;
using System.Linq;
using System.Net;
using System.Net.Http;
using System.Net.Http.Headers;
using System.Net.Security;
using System.Security.Cryptography;
using System.Text;
using System.Threading.Tasks;
using System.Web.Http;
using System.Web.Http.Cors;
using System.Web.Script.Serialization;

namespace ApiTng.Controllers
{
    [EnableCors(origins: "*", headers: "*", methods: "*")]
    public class Sale_OrderUpdateController : ApiController
    {
        private static IMemberDal _MemberDal;
        private static ISale_OrdersDal _saleOrdersDal;
        private static Logger _logger;
        private static ICompanyDal _CompanyDal;
        private VIETTELService api;
        private Api apiconnect;
        private string tokenkey = "SDYTLSOFT@1234554321";

        public Sale_OrderUpdateController()
        {
            _MemberDal = new MemberDal();
            _saleOrdersDal = new Sale_OrdersDal();
            _CompanyDal = new CompanyDal();
            _logger = LogManager.GetCurrentClassLogger();
            api = new VIETTELService();
            apiconnect = new Api();
        }

       

        [HttpPost]
        public ResponeResult UpdateExpressBE(Sale_OrderUpdateExpress obj)
        {
            var response = new ResponeResult(ConstUtil.Error, "Có lỗi xảy ra!", null);
            try
            {
                var dataload = _saleOrdersDal.UpdateExpress(obj);
                if (dataload)
                {
                    response.Status = ConstUtil.Success;
                    response.Message = "Thành công !";
                    response.Data = dataload;
                    return response;
                }
                response.Status = ConstUtil.Error;
                response.Message = "Có lỗi sảy ra !";
                return response;
            }
            catch (Exception ex)
            {
                _logger.Error(ex.Message);
                response.Status = ConstUtil.Error;
                response.Message = "Có lỗi sảy ra !";
                return response;
            }
        }

        


    }
}